classdef RDATFile
    properties
        version
        name
        sequence
        structure
        offset
        seqpos
        mutpos
        annotations
        comments
        data_annotations
        area_peak
        area_peak_error
        xsel
        xsel_refine
        trace
    end
end
