classdef RDATFile
    properties
        version
        name
        sequence
        structure
        offset
        seqpos
        mutpos
        annotations
        comments
        data_annotations
	reactivity
        reactivity_error
        xsel
        xsel_refine
        trace
    end
end
